//
//  DummyData.swift
//  FoldableCellExample
//
//  Created by 김민성 on 3/24/25.
//

import UIKit

let dummySettings: [SettingItem] = [
    SettingItem(title: "Wi-Fi",
                icon: UIImage(systemName: "wifi"),
                description1: "Connected to Home Network",
                description2: "192.168.1.1"),
    
    SettingItem(title: "Bluetooth",
                icon: UIImage(systemName: "bolt.horizontal"),
                description1: "On",
                description2: "Connected to AirPods"),
    
    SettingItem(title: "Airplane Mode",
                icon: UIImage(systemName: "airplane"),
                description1: "Off",
                description2: "Disabled"),
    
    SettingItem(title: "Notifications",
                icon: UIImage(systemName: "bell"),
                description1: "Enabled",
                description2: "5 unread"),
    SettingItem(title: "Sound & Haptics",
                icon: UIImage(systemName: "speaker.wave.2"),
                description1: "Volume: 50%",
                description2: "Haptics: On"),
    SettingItem(title: "Screen Time",
                icon: UIImage(systemName: "hourglass"),
                description1: "Daily Average: 3h 15m",
                description2: "Limit: None"),
    SettingItem(title: "General",
                icon: UIImage(systemName: "gear"),
                description1: "Software Update Available",
                description2: "Version 17.1"),
    SettingItem(title: "Privacy & Security",
                icon: UIImage(systemName: "lock.shield"),
                description1: "Location Services: On",
                description2: "App Tracking: Limited"),
    SettingItem(title: "Battery",
                icon: UIImage(systemName: "battery.100"),
                description1: "Battery Health: 85%",
                description2: "Last Charge: 92%"),
    SettingItem(title: "Display & Brightness",
                icon: UIImage(systemName: "sun.max"),
                description1: "Brightness: 75%",
                description2: "Dark Mode: Off"),
    SettingItem(title: "Wallpaper",
                icon: UIImage(systemName: "photo"),
                description1: "Current: Default",
                description2: "Perspective Zoom: On"),
    SettingItem(title: "Siri & Search",
                icon: UIImage(systemName: "mic"),
                description1: "Hey Siri: On",
                description2: "Suggestions: Enabled"),
    SettingItem(title: "Face ID & Passcode",
                icon: UIImage(systemName: "faceid"),
                description1: "Face ID: Enabled",
                description2: "Passcode: Set"),
    SettingItem(title: "Emergency SOS",
                icon: UIImage(systemName: "exclamationmark.triangle"),
                description1: "Hold Side Button: On",
                description2: "Contacts: 2"),
    SettingItem(title: "App Store",
                icon: UIImage(systemName: "app.badge"),
                description1: "Auto Updates: On",
                description2: "In-App Purchases: Enabled"),
    SettingItem(title: "Wallet & Apple Pay",
                icon: UIImage(systemName: "creditcard"),
                description1: "Cards: 3",
                description2: "Transactions: Enabled"),
    SettingItem(title: "Passwords & Accounts",
                icon: UIImage(systemName: "key"),
                description1: "Saved Passwords: 45",
                description2: "AutoFill: On"),
    SettingItem(title: "Mail",
                icon: UIImage(systemName: "envelope"),
                description1: "Accounts: 2",
                description2: "Unread: 8"),
    SettingItem(title: "Contacts",
                icon: UIImage(systemName: "person.2"),
                description1: "Synced: iCloud",
                description2: "Favorites: 12"),
    SettingItem(title: "Calendar",
                icon: UIImage(systemName: "calendar"),
                description1: "Next Event: Meeting at 3 PM",
                description2: "Reminders: 2"),
]
